# Generated by Django 5.2.6 on 2025-09-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_category_task_category_comment_tasklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Niski'), ('medium', 'Sredni'), ('high', 'Wysoki')], default='medium', max_length=10),
        ),
    ]
