# Generated by Django 5.2.6 on 2025-11-21 16:19

from django.db import migrations, models


def seed_status_priority(apps, schema_editor):
    Status = apps.get_model('tasks', 'TaskStatusOption')
    Priority = apps.get_model('tasks', 'TaskPriorityOption')
    default_statuses = [
        ('todo', 'Do zrobienia', 1),
        ('in_progress', 'W trakcie', 2),
        ('done', 'Zakończone', 3),
    ]
    default_priorities = [
        ('low', 'Niski', 1),
        ('medium', 'Średni', 2),
        ('high', 'Wysoki', 3),
    ]
    for value, label, order in default_statuses:
        Status.objects.get_or_create(value=value, defaults={'label': label, 'order': order})
    for value, label, order in default_priorities:
        Priority.objects.get_or_create(value=value, defaults={'label': label, 'order': order})


def unseed_status_priority(apps, schema_editor):
    Status = apps.get_model('tasks', 'TaskStatusOption')
    Priority = apps.get_model('tasks', 'TaskPriorityOption')
    Status.objects.filter(value__in=['todo', 'in_progress', 'done']).delete()
    Priority.objects.filter(value__in=['low', 'medium', 'high']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_googlecredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPriorityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatusOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='todo', max_length=50),
        ),
        migrations.RunPython(seed_status_priority, unseed_status_priority),
    ]
